SportsMGMTApp/Controllers/ContractController.cs
namespace SportsMGMTApp.Controllers
{
    using SportsMGMTApp.Filters;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using SportsMGMTBLL;
    using SportsMGMTCommon;
    using SportsMGMTApp.Models;
    using Interfaces.IBusinessLogic;
    using SportsMGMTBLL.IOC;

    public class ContractController : Controller
    {
        IContracts contractsBLL;
        IUser users;
        public ContractController(IContracts contracts, IUser user)
        {
            contractsBLL = contracts;
            users = user;
        }
        //list all contracts
        [HttpGet]
        [MustBeInRole(Roles ="Admin,Coach")]
        public ActionResult ListContracts()
        {


            List<Contracts> getContracts = new List<Contracts>();

            //store List of Teams in Model
            getContracts = contractsBLL.GetContracts();

            //send to view


            return View(getContracts);
        }
        //update get with id table only
        [HttpGet]
        [MustBeInRole(Roles="Admin")]
        public ActionResult UpdateContracts(int id)
        {
        
            //create model
            ContractModel contract = new ContractModel(users);

            contract.Contract = contractsBLL.GetContracts().Find(m => m.ContractID == id);

            contract.ContractID = contract.Contract.ContractID;
            contract.ContractType = contract.Contract.ContractType;
            contract.Salary = contract.Contract.Salary;

            return View(contract);
        }
        //post update of contract
        [HttpPost]
        [MustBeInRole(Roles="Admin")]
        public ActionResult UpdateContracts(ContractModel contract)
        {
            if (ModelState.IsValid)
            {
                //set Variables to object
                Contracts contractUpdate = new Contracts();
                contractUpdate.ContractID = contract.ContractID;
                contractUpdate.ContractType = contract.ContractType;
                contractUpdate.Salary = contract.Salary;
                Contracts contractCheck = contractsBLL.GetContracts().Find(m => m.ContractID == contract.ContractID);
                contractsBLL.UpdateContract(contractUpdate);

                Contracts contracts = contractsBLL.GetContracts().Find(m => m.ContractID == contract.ContractID);

                //compare if update successful

                if (contracts != contractCheck)
                {
                    ViewBag.Message = "Update Successful";
                }
                else
                {
                    ViewBag.Message = "Update Failed";
                }
            }
            else
            {
                ViewBag.Message = "Model State Not Valid";
            }
            return View(contract);
        }
        //create contract
        [HttpGet]
        [MustBeInRole(Roles="Coach,Admin")]
        public ActionResult CreateContract()
        {
            return View();
        }
        //creates a new contract on post
        [HttpPost]
        [MustBeInRole(Roles = "Coach,Admin")]
        public ActionResult CreateContract(ContractModel contract)
        {
            if (ModelState.IsValid)
            {

                Contracts createContract = new Contracts();
                createContract.ContractType = contract.ContractType;
                createContract.Salary = contract.Salary;
                contractsBLL.CreateContracts(createContract);

                bool check = contractsBLL.GetContracts().Exists(m => m.ContractType == createContract.ContractType);

                if (check)
                {
                    ViewBag.Message = "Contract Created";
                }
                else
                {
                    ViewBag.Message = "Contract not Created";
                }
                    
            }
            else
            {
                ViewBag.Message = "Model State Not Valid";
            }

            return View(contract);
        }
        //deletes contract on id off table only
        [HttpGet]
        [MustBeInRole(Roles = "Admin")]
        public ActionResult DeleteContract(int id)
        {


            Contracts contracts = contractsBLL.GetContracts().Find(m => m.ContractID == id);

            ContractModel contractModel = new ContractModel(users);

            contractModel.ContractID = contracts.ContractID;
            contractModel.ContractType = contracts.ContractType;
            contractModel.Salary = contracts.Salary;

            return View(contractModel);
        }

        [HttpPost]
        [MustBeInRole(Roles = "Admin")]
        public ActionResult DeleteContract(ContractModel contract)
        {

            //Find Object
            Contracts contracts = contractsBLL.GetContracts().Find(m => m.ContractID == contract.ContractID);
            //Delete Object
            contractsBLL.DeleteContracts(contracts);
            //Check if it exists still
            bool check = contractsBLL.GetContracts().Exists(m => m.ContractID == contract.ContractID);
            //if it does 
            if (check)
            {
                //delete failed
                ViewBag.Message = "Delete Failed";
            }
            else
            {
                ViewBag.Message = "Delete Successful";
            }

            return View(contract);
        }


    }
}

SportsMGMTApp/Views/Contract/CreateContract.cshtml
@model SportsMGMTApp.Models.ContractModel

@{

    if (ViewBag.Message == "Contract Created")
    {
        //display success message in green boarder
        <div class="alert alert-success" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message == "Contract not Created")
    {
        //display red message if exception thrown
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message == "Model State Not Valid")
    {
        //display red message if exception thrown
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else
    {

    }
}

@using (Html.BeginForm("CreateContract","Contract"))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ContractType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContractType, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContractType, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
        </div>
    </div>

  
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
}

SportsMGMTApp/Views/Contract/DeleteContract.cshtml
@model SportsMGMTApp.Models.ContractModel

@{
    if (ViewBag.Message == "Delete Failed")
    {
        // display success message in green boarder
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message == "Delete Successful")
    {
        //display success message in green boarder
        <div class="alert alert-success" role="alert">
            @ViewBag.Message
        </div>
    }
    else
    {

    }

}
<a href=@Url.Action("ListContracts", "Contract") class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">Back to List</span>
</a>
@using (Html.BeginForm("DeleteContract","Contract"))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ContractID)

    <div class="form-group">
        @Html.LabelFor(model => model.ContractType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContractType, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContractType, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" onclick="return confirm('Delete Contract?')" value="Delete" class="btn btn-primary" />
        </div>
    </div>
}

SportsMGMTApp/Views/Contract/ListContracts.cshtml
@model List<SportsMGMTCommon.Contracts>

@{
    var user = Session["Users"] as SportsMGMTCommon.Users;
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">All Contracts</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Contract Type
                        </th>
                        <th>
                            Salary
                        </th>
                        @{ if (user.RoleID == 1) {
                        <th>Update/Delete</th>
                                }
                            }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ContractType)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Salary)
                            </td>
                            @{ if (user.RoleID == 1)
                                {
                            <td>
                                @Html.ActionLink("Edit", "UpdateContracts", new { id = item.ContractID }) |
                                @Html.ActionLink("Delete", "DeleteContract", new { id = item.ContractID })
                            </td>
                                }
                                else
                                {

                                }
                                }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<a href=@Url.Action("CreateContract", "Contract") class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">Create Contracts</span>
</a>

SportsMGMTApp/Views/Contract/UpdateContracts.cshtml
@model SportsMGMTApp.Models.ContractModel

@{

    if (ViewBag.Message == "Update Successful")
    {
        //display success message in green boarder
        <div class="alert alert-success" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message == "Update Failed")
    {
        //display red message if exception thrown
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message == "Model State Not Valid")
    {
        // display success message in green boarder
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else
    {

    }
}
<a href=@Url.Action("ListContracts", "Contract") class="btn btn-primary btn-icon-split">
<span class="icon text-white-50">
    <i class="fas fa-flag"></i>
</span>
<span class="text">Back to List</span>
</a>
<br />
@using (Html.BeginForm("UpdateContracts","Contracts"))
{



    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ContractID)

    <div class="form-group">
        @Html.LabelFor(model => model.ContractType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContractType, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContractType, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Update" class="btn btn-primary" />
        </div>
    </div>
}