SportsMGMTApp/Controllers/GameController.cs
namespace SportsMGMTApp.Controllers
{
    using SportsMGMTApp.Filters;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using SportsMGMTApp.Models;
    using SportsMGMTApp.Mapper;
    using SportsMGMTBLL;
    using SportsMGMTCommon;
    using System;
    using Interfaces.IBusinessLogic;
    using SportsMGMTBLL.IOC;

    public class GameController : Controller
    {
        IGame gameBLL;
        ITeam team;
        public GameController(IGame games,ITeam teams)
        {
            gameBLL = games;
            team = teams;
        }
        // Create Post
        [HttpPost]
        [MustBeLoggedIn]
        [MustBeInRole(Roles="Admin")]
        public ActionResult Game(GameModel game)
        {

            if (ModelState.IsValid)
            {
                if (game.StartTime == DateTime.MinValue || game.EndTime==DateTime.MinValue)
                {
                    ViewBag.Message = "DateTime Cannot be the Beggining of time";
                    return View(game);
                }
                else if (game.StartTime > game.EndTime)
                {
                    ViewBag.Message = "Game Start Time cannot be greater than end time";
                    return View(game);
                }
                else if (game.EndTime < game.StartTime)
                {
                    ViewBag.Message = "Game End Time cannot be less than start time";
                    return View(game);
                }
                //Create Map
                GameMapper mapGame = new GameMapper();
                Game addGame = mapGame.MapGame(game);
                
                if (addGame.HomeTeam == addGame.AwayTeam)
                {
                    ViewBag.Message = "Home Team Cannot Be the Same as Away Team?";
                    return View(game);
                }
                else
                {
                    gameBLL.CreateGame(addGame);
                }
                //check insert added
                List<Game> checkGame = gameBLL.GetGames();
                if (checkGame.Exists(m => m.StartTime == addGame.StartTime))
                {
                    ViewBag.Message = "Game Created!";
                }
                else
                {
                    ViewBag.Message = "Game Failed!";
                }

            }
            return View(game);

        }
        // Create Get
        [HttpGet]
        [MustBeInRole(Roles = "Admin")]
        public ActionResult Game()
        {
            GameModel model = new GameModel(gameBLL,team);
            return View(model);
        }
        //Update Get
        [HttpGet]
        [MustBeLoggedIn]
        [MustBeInRole(Roles = "Admin")]
        //passes in the model the form action has a get for state changes
        public ActionResult UpdateGame(int id)
        {

            GameModel gameModel = new GameModel(gameBLL,team);
            List<Game> getGame = gameModel.GetGames();
            gameModel.game = getGame.Find(m => m.GameID == id);
            return View(gameModel);
        }
        //UpdatePost
        [HttpPost]
        [MustBeInRole(Roles = "Admin")]
        //when user post Save it will call the BLL update function to update the database and reset the non update parameters to same values
        public ActionResult UpdateGame(GameModel model)
        {

            if (ModelState.IsValid)
            {
                bool check = gameBLL.UpdateGame(model.game);
                //Display Update successful if update occured
                if (check)
                {
                    ViewBag.Message = "Update Successful";
                }
                else
                {
                    ViewBag.Message = "Update Failed!";
                }

            }
            return View(model);
        }
        //Read Get
        [HttpGet]
        [MustBeLoggedIn]
        [MustBeInRole(Roles = "Admin,Coach,Player")]
        public ActionResult ListGame()
        {
            GameModel gameModel = new GameModel(gameBLL,team);
            List<Game> getGames = gameModel.GetGames();
            return View(getGames);
        }
        //Delete Get
        [MustBeInRole(Roles="Admin")]
        [MustBeLoggedIn]
        [HttpGet]
        public ActionResult DeleteGame(int id)
        {

            GameModel gameModel = new GameModel(gameBLL,team); // create a new model
            List<Game> getGame = gameModel.GetGames(); //store a list of games
            gameModel.game = getGame.Find(m => m.GameID == id); //store in the model objects common game object the object from the list
            return View(gameModel);
        }
        //Delete Post
        [MustBeLoggedIn]
        [MustBeInRole(Roles="Admin")]
        [HttpPost]
        public ActionResult DeleteGame(GameModel model)
        {
           
                Game game = model.GetGames().Find(m => m.GameID == model.game.GameID);
                gameBLL.DeleteGame(model.game); // delete game by using the common object game in the model
                List<Game> checkGame = model.GetGames(); //get a list of games curently
                bool check = checkGame.Exists(m => m.GameID == model.game.GameID); //store in a bool if the game still exists thats deleted
                if (check) //if it still exists
                {
                    ViewBag.Message = "Delete Failed";
                }
                else if(check==false)
                {
                    ViewBag.Message = "Delete Successful";
                }
            else
            {

            }
                model.game = game;
            return View(model);
        }
    }
}

SportsMGMTApp/Controllers/UserController.cs
namespace SportsMGMTApp.Controllers
{
    using DHTMLX.Scheduler;
    using DHTMLX.Scheduler.Data;
    using SportsMGMTApp.Filters;
    using SportsMGMTApp.Mapper;
    using SportsMGMTApp.Models;
    using SportsMGMTBLL;
    using SportsMGMTCommon;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using System.Configuration;
    using Interfaces.IBusinessLogic;

    /// <summary>
    /// The controller for the majority of user CRUD
    /// </summary>
    public class UserController : Controller
    {
        //inject interfaces into controller here
        IUser userBLL;
        IRole rolesBLL;
        ITeam team;
        IGame gameBLL;
        IPractice practiceBLL;
        IContracts contractsBLL;
        IAttendanceBLL attend;
        public UserController(IUser user, IRole role, ITeam teams, IGame game, IPractice practice,IContracts contracts, IAttendanceBLL attendance)
        {
            userBLL = user;
            rolesBLL = role;
            team = teams;
            gameBLL = game;
            practiceBLL = practice;
            contractsBLL = contracts;
            attend = attendance;
        }
        //CRUD for user as well as sending Emails More detailed comments in method
        /// <summary>
        /// The GET for the User Register view 
        /// </summary>
        /// <returns> user register view to create user</returns>
        public ActionResult UserRegister()
        {
            //show view
            return View();
        }
        /// <summary>
        /// The POST for user Register that  creates a new user
        /// </summary>
        /// <param name="user"></param>
        /// <returns> redirects to Login page</returns>
        [HttpPost]
        public ActionResult UserRegister(UserRegister user)
        {
            bool check = false;
            if (ModelState.IsValid)
            {
                UserMapper UserMap = new UserMapper();
                //set the user variable through method in mapper class

                Users insert = UserMap.SendToBLL(user);


                //create a list object to store current list of users

                List<Users> checkUser = userBLL.GetUsers();

                //check to see if the User already exist in database
                //check if user already exists with that UserName for data validation purposes for my DA method

                if (checkUser.Exists(m => m.UserName == insert.UserName))
                {
                    ViewBag.Message = "User Already Exist with that UserName";
                    return View(user);
                }
                else if (checkUser.Exists(m => m.Email == insert.Email))
                {
                    ViewBag.Message = "User Already Exists with that E-mail";
                    return View(user);
                }
                else
                {
                    //Call BLL method to insert the new user from view model and store success into a bool variable
                    check = userBLL.InsertNewUser(insert);
                }


            }
            else
            {
                ViewBag.Message = "Invalid Entry!";
                return View(user);
            }

            return Redirect("~\\User\\Login");

        }
        /// <summary>
        /// The Get for the forgot Password VIEW
        /// </summary>
        /// <returns> the view </returns>
        [HttpGet]
        public ActionResult ForgotPassword()
        {
            //return empty view to collect the username
            return View();
        }
        /// <summary>
        /// Posts the forgot password action
        /// </summary>
        /// <param name="username"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ForgotPassword(string username)
        {

            //check if the user exists 
            var dash = Session["Dash"] as DashBoard;
            dash.Message = username;
                bool check = userBLL.GetUsers().Exists(m => m.UserName == username);

                if (check) //if the user exists
                {
                    //redirect them to the password change view
                    return Redirect("~\\User\\PasswordChange");
                }
                else
                {   //change the session object message to user does not exist and return view with the username
                    ViewBag.Message = "User Does Not Exist with that UserName";
                return View();
            }
        }
        [HttpGet]
        public ActionResult PasswordChange()
        {
         //store dashboard set properties from username into an object
        //find the user with the message username passed from Forgot Password view

        var dash = Session["Dash"] as DashBoard;
        Users user = userBLL.GetUsers().Find(m => m.UserName == dash.Message);
            //store the users information into a LoginUser Model
            LoginUser login = new LoginUser
            {
                UserName = user.UserName,
                Password = user.Password
            };


            //pass model into view
            return View(login);
        }
        [HttpPost]
       public  ActionResult PasswordChange(LoginUser users)
        {
            if (ModelState.IsValid)
            {   //create a user BLL instance

                //Store update object into a common class object
                Users updateUser = userBLL.GetUsers().Find(m => m.UserName == users.UserName);
                //Store a check to see if update successful
                Users checkUser = userBLL.GetUsers().Find(m => m.UserName == users.UserName);
                //set update user object pass word to the password passed in by the model
                updateUser.Password = users.Password;
                //perform update
                userBLL.UpdateUser(updateUser);
                //check if the user has been updated by searching for all matching passwords first then to filter duplicates by unique username
                Users checkMethod = userBLL.GetUsers().FindAll(m => m.Password == updateUser.Password).Find(m => m.UserName == updateUser.UserName);
                //if the objects are not the same as the original object
                if (checkUser != checkMethod)
                {
                    //Create a New Session Variable
                    var dash = Session["Dash"] as DashBoard;
                    //set message as password changed
                    ViewBag.Message = "Password changed";
                    //send email to the users e-mail address notifying them of the change to password
                    Email email = new Email
                    {
                        Message = ConfigurationManager.AppSettings.Get("Message"),
                        FromName = ConfigurationManager.AppSettings.Get("Name"),
                        Subject = ConfigurationManager.AppSettings.Get("Subject"),
                        UserName = ConfigurationManager.AppSettings.Get("UserName"),
                        To = updateUser.Email
                    };
                    //use the send emails method from the home controllers
                    HomeController.SendEmails(email);
                    //Redirect to Login to display session message that password has changed

                }
                else
                {
                    ViewBag.Message = "Update Failed";
                    return View(users);
                }

            }
            else
            {
                ViewBag.Message = "Invalid Entry";
                return View(users);
            }
            return Redirect(ConfigurationManager.AppSettings.Get("Action"));
        }
        [HttpGet]
        public ActionResult Login()
        {
            Session["Dash"] = new DashBoard(); 
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginUser loginUser)
        {
            if (ModelState.IsValid)
            {
                //Call mapper object to mapp items to the database
                UserMapper userMapper = new UserMapper();
                Users login = userMapper.LoginBLLMapper(loginUser);
                //call BLL layer

                Users loginUsers = userBLL.GetUsersByUserName(login.UserName);
                //display login successful or failed due to input error
                //if (loginUsers.Password is null) //BUG: Database connectivity has been an issue here is a patch for users not edited by admin
                //{
                //    Session["Users"] = loginUsers;
                //    return Redirect("~/User/NewUserHome");
                //}
                if (loginUsers.Password !=loginUser.Password)
                {
                    ViewBag.Message = "Invalid UserName and/or Password";
                    return View(loginUser);
                }
                //Call roles BLL

               Roles role = rolesBLL.GetRoles().Find(m=>m.RoleID==loginUsers.RoleID);
                if (role.RoleType != null)
                {
                    //DO NOT REMOVE
                    Session["Roles"] = role.RoleType;
                }
                else
                {
                    Session["Roles"] = Roles.Null.RoleType;
                }
                Session["UserName"] = loginUsers.UserName;
                //DO NOT REMOVE
                Session["Users"] = loginUsers;
                if (loginUsers.RoleID != Roles.Null.RoleID)
                {
                    MeaningfulCalculation calculations = new MeaningfulCalculation(attend, userBLL, team, contractsBLL, practiceBLL, gameBLL);

                    Session["Dash"] = calculations.ReturnDashBoard(loginUsers); 
                }
                //display login successful or failed
                    if (loginUsers.RoleID == Users.Null.UserID)
                    {

SportsMGMTApp/Views/Game/DeleteGame.cshtml
@model SportsMGMTApp.Models.GameModel

@{
    ViewBag.Title = "DeleteGame";

}

<a href=@Url.Action("ListGame", "Game") class="btn btn-primary btn-icon-split">
<span class="icon text-white-50">
    <i class="fas fa-flag"></i>
</span>
<span class="text">Back to List</span>
</a>
 
    @{
        if (ViewBag.Message == "Delete Successful")
        {
            //display success message in green boarder
            <div class="alert alert-success" role="alert">
                @ViewBag.Message
            </div>
        }
        else if (ViewBag.Message == "Delete Failed")
        {
            //display red message if exception thrown
            <div class="alert alert-danger" role="alert">
                @ViewBag.Message
            </div>
        }
        else
        {

        }

    }
    @using (Html.BeginForm("DeleteGame","Game"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Delete Game</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.game.GameID)
            <div class="form-group">
                @Html.LabelFor(model => model.game.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.game.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.game.StartTime, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.game.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.game.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.game.EndTime, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.game.HomeTeam, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.FormatValue(Model.game.HomeTeam, SportsMGMTApp.Models.GameModel.GetTeamNameString(Model.game.HomeTeam))
                    @Html.ValidationMessageFor(model => model.HomeTeam, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.game.AwayTeam, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.FormatValue(Model.game.AwayTeam,SportsMGMTApp.Models.GameModel.GetTeamNameString(Model.game.AwayTeam))
                    @Html.ValidationMessageFor(model => model.AwayTeam, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.game.HomeTeamScore, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.game.HomeTeamScore, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.game.HomeTeamScore, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.game.AwayTeamScore, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.game.AwayTeamScore, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.game.AwayTeamScore, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <button type="submit" onclick="return confirm('Are you sure you want to delete?')" class="btn btn-primary">Delete</button>
            </div>
        </div>
    }

SportsMGMTApp/Views/Game/Game.cshtml
@model SportsMGMTApp.Models.GameModel

@{
    ViewBag.Title = "Game";
}

<h2>Create New Game</h2>
@{
    if (ViewBag.Message == "Game Created!")
    {
        //display red message if exception thrown
        <div class="alert alert-success" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message == "Game Failed!")
    {
        //display red message if exception thrown
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message == "Home Team Cannot Be the Same as Away Team?")
    {
        //display red message if exception thrown
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message != null)
    {
        //display fail message if exception thrown
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else
    {

    }
}
<a href=@Url.Action("Calendar","User") class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">Back to Calendar</span>
</a>
@using (Html.BeginForm("Game","Game"))
{
    @Html.AntiForgeryToken()

    <div class="container-fluid">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control", @placeholder = "Start Time" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control", @placeholder = "End Time" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomeTeam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.HomeTeam, Model.GetTeam, "TeamName", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomeTeam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AwayTeam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AwayTeam, Model.GetTeam, "TeamName", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AwayTeam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomeTeamScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomeTeamScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomeTeamScore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AwayTeamScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AwayTeamScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AwayTeamScore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" />

            </div>
        </div>
    </div>
}

SportsMGMTApp/Views/Game/ListGame.cshtml
@model List<SportsMGMTCommon.Game>

@{ 
    ViewBag.Titlr = "View Games";
    var user = Session["Users"] as SportsMGMTCommon.Users;
}


<h2>View Games</h2>

@{ if (user.RoleID == 1) {
<a href=@Url.Action("Game", "Game") class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">InsertGame</span>
</a>
    }
    else
    {

    }
    }
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">All Games</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Start-Time
                        </th>
                        <th>
                            End-Time
                        </th>
                        <th>
                            Home Team
                        </th>
                        <th>Away Team</th>
                        <th>Home Team Score</th>
                        <th>Away Team Score</th>
                        @if (user.RoleID==1)
                        {
                        <th>Update/Delete</th>
                        }
                        else
                        {

                        }
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.StartTime)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.EndTime)
                            </td>
                            <td>
                                @Html.FormatValue(item.HomeTeam, SportsMGMTApp.Models.GameModel.GetTeamNameString(item.HomeTeam))
                            </td>
                            <td>
                                @Html.FormatValue(item.AwayTeam, SportsMGMTApp.Models.GameModel.GetTeamNameString(item.AwayTeam))
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.HomeTeamScore)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AwayTeamScore)
                            </td>
                            @{ 
                                if (user.RoleID == 1)
                                {
                            <td>
                                @Html.ActionLink("Edit", "UpdateGame", new { id = item.GameID }) |
                                @Html.ActionLink("Delete", "DeleteGame", new { id = item.GameID })
                            </td>
                                }
                                else
                                {

                                }
                                }
                            <td>
                                @Html.HiddenFor(modelItem => item.GameID)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

SportsMGMTApp/Views/Game/UpdateGame.cshtml
@model SportsMGMTApp.Models.GameModel

@{
    ViewBag.Title = "UpdateGame";
}
@{

    if (ViewBag.Message == "Update Successful")
    {
        //display red message if exception thrown
        <div class="alert alert-success" role="alert">
            @ViewBag.Message
        </div>
    }
    else if(ViewBag.Message=="Update Failed!")
    {
        //display red message if exception thrown
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
}
@using (Html.BeginForm("UpdateGame","Game"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Game Update</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" }) 
        @Html.HiddenFor(model =>model.game.GameID)
    <div class="form-group">
        @Html.LabelFor(model => model.game.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.game.StartTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.game.StartTime, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.game.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.game.EndTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.game.EndTime, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.game.HomeTeam, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.game.HomeTeam, Model.GetTeam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HomeTeam, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.game.AwayTeam, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.game.AwayTeam, Model.GetTeam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AwayTeam, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.game.HomeTeamScore, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.game.HomeTeamScore, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.game.HomeTeamScore, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.game.AwayTeamScore, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.game.AwayTeamScore, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.game.AwayTeamScore, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Update</button>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "ListGame")
</div>