SportsMGMTApp/Controllers/AttendanceController.cs
namespace SportsMGMTApp.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;
    using SportsMGMTApp.Models;
    using SportsMGMTApp.Filters;
    using SportsMGMTBLL;
    using SportsMGMTCommon;
    using Interfaces.IBusinessLogic;
    using Interfaces.IDataAccess;
    using SportsMGMTBLL.IOC;

    public class AttendanceController : Controller
    {
        IAttendanceBLL attendance;
        IUser usersBLL;
        IPractice practiceBLL;
        IGame gameBLL;
        ITeam team;
        public AttendanceController(IAttendanceBLL attend, IUser user,IPractice practice, IGame game,ITeam teams)
        {
            attendance = attend;
            usersBLL = user;
            practiceBLL = practice;
            gameBLL = game;
            team = teams;
        }
        // GET: Attendance
        [HttpGet]
        [MustBeInRole(Roles="Coach,Admin")]
        public ActionResult ViewGameAttendance()
        {
            
            var userInfo = Session["Users"] as Users;
            List<GameAttendance> games = attendance.getGameAttendaned();
            //get the list of users for only that team
            List<Users> users = usersBLL.GetUsers().FindAll(m => m.TeamID == userInfo.TeamID);
            //create a new list to store attendance for only that team
            List<GameAttendance> viewAttendanceByTeam = new List<GameAttendance>();
            //for each user in the coaches team
            foreach(Users user in users)
            {
                //find the users attendance
                GameAttendance game = games.Find(m => m.UserID == user.UserID);
                //add to list that sorts attendance by team
                viewAttendanceByTeam.Add(game);
            }
            return View(viewAttendanceByTeam);
        }
        //List Attendance for creation of new attendance
        [HttpGet]
        [MustBeInRole(Roles="Admin,Coach")]
        public ActionResult ListAttendance()
        {
            var users = Session["Users"] as Users;
            List<Practice> getAllPractice = practiceBLL.GetPractice().FindAll(m => m.TeamID == users.TeamID);


            return View(getAllPractice);
        }
        //list attendance for creation of game *To implement later
        [HttpGet]
        [MustBeInRole(Roles="Admin,Coach")]
        public ActionResult ListGameAttendance()
        {
            var users = Session["Users"] as Users;
            List<Game> getAllGame = gameBLL.GetGames().FindAll(m => m.AwayTeam == users.TeamID);
            getAllGame.AddRange(gameBLL.GetGames().FindAll(m => m.HomeTeam == users.TeamID));

            return View(getAllGame);
        }
        //list practice attendance
        [HttpGet]
        [MustBeInRole(Roles="Admin,Coach")]
        public ActionResult ListPracticeAttendance()
        {
            var Users=Session["Users"] as Users;

            List<PracticeAttended> practice = attendance.getPracticeAttendaned(Users.TeamID);

            return View(practice);
        }
        //create game attendance
        [HttpGet]
        [MustBeInRole(Roles="Admin,Coach")]
        public ActionResult CreateGameAttendance(int id)
        {
            GameAttendanceModel model = new GameAttendanceModel(gameBLL,team,usersBLL,attendance);
            model.GameID = id;

            return View(model);
        }
        [HttpPost]
        [MustBeInRole(Roles="Admin,Coach")]
        public ActionResult CreateGameAttendance(GameAttendanceModel model)
        {
            if (ModelState.IsValid)
            {
                var user = Session["Users"] as Users;
                GameAttendance gameAttendance = new GameAttendance
                {
                    GameID = model.GameID,
                    UserID = model.UserID,
                    Attended = model.Attended
                };

                List<GameAttendance> duplicateCheck = attendance.getGameAttendaned();
                bool duplicateEntry = duplicateCheck.Exists(m => m.UserID == model.UserID && m.GameID == model.GameID);
                if (duplicateEntry)
                {
                    ViewBag.Message = "User already has attendance recorded";
                    return View(model);
                }
                else
                {
                    attendance.CreateGameAttance(gameAttendance);
                }

                //check if insert added
                List<GameAttendance> check = attendance.getGameAttendaned();
                bool verify = check.Exists(m => m.UserID == model.UserID);

                if (verify)
                {
                    ViewBag.Message = "Attendance Added";

                }
                else
                {
                    ViewBag.Message = "Creation Failed";
                }
            }
            else
            {
                ViewBag.Message = "Model State is not Valid";
                return View(model);
            }

            return View(model);
        }
        //create practice attendance
        [HttpGet]
        [MustBeInRole(Roles = "Admin,Coach")]
        public ActionResult CreatePracticeAttendance(int id)
        {
            PracticeAttendanceModel model = new PracticeAttendanceModel(usersBLL, practiceBLL);
            model.PracticeID = id;

            return View(model);
        }
        [HttpPost]
        [MustBeInRole(Roles="Admin,Coach")]
        public ActionResult CreatePracticeAttendance(PracticeAttendanceModel model)
        {
            if (ModelState.IsValid)
            {
                var user = Session["Users"] as Users;
                PracticeAttended practice = new PracticeAttended
                {
                    PracticeID = model.PracticeID,
                    UserID = model.UserID,
                    Attended = model.Attended
                };


                List<PracticeAttended> check = attendance.getPracticeAttendaned(user.TeamID);
                bool duplicateEntry = check.Exists(m => m.UserID == model.UserID && m.PracticeID == model.PracticeID);
                if (duplicateEntry)
                {
                    ViewBag.Message = "User Already has been entered for this practice";
                    return View(model);
                }
                else
                {
                    attendance.CreatePracticeAttendance(practice);
                }

                //check if insert added
                List<PracticeAttended> checkAgain = attendance.getPracticeAttendaned(user.TeamID);
                bool verify = checkAgain.Exists(m => m.UserID == model.UserID && m.PracticeID==model.PracticeID);

                if (verify)
                {
                    ViewBag.Message = "Attendance Added";

                }
                else
                {
                    ViewBag.Message = "Creation Failed";
                }
            }
            else
            {
                ViewBag.Message = "Model State is not Valid";
                return View(model);
            }

            return View(model);
        }
    }
}

SportsMGMTApp/Views/Attendance/CreateGameAttendance.cshtml
@model SportsMGMTApp.Models.GameAttendanceModel

@{
    var users = Session["Users"] as SportsMGMTCommon.Users;

    if (ViewBag.Message == "Attendance Added")
    {
        //display success message if added
        <div class="alert alert-success" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message == "Creation Failed")
    {
        //display fail message if exception thrown
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message == "Model State is not Valid")
    {
        //display fail message if exception thrown
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message == "User already has attendance recorded")
    {
        //display fail message if exception thrown
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message != null)
    {
        //display fail message if exception thrown
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else
    {

    }
}
<a href=@Url.Action("ListGameAttendance", "Attendance") class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">Back to List</span>
</a>

@using (Html.BeginForm("CreateGameAttendance","Attendance"))
{
    <div class="form-group">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GameID)
        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.UserID, Model.GetUsers(users.TeamID), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Attended, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Attended)
                    @Html.ValidationMessageFor(model => model.Attended, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


<a href=@Url.Action("ViewGameAttendance", "Attendance") class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">View All Game Attendance</span>
</a>

SportsMGMTApp/Views/Attendance/CreatePracticeAttendance.cshtml
@model SportsMGMTApp.Models.PracticeAttendanceModel

@{
    var users = Session["Users"] as SportsMGMTCommon.Users;

    if (ViewBag.Message == "Attendance Added")
    {
        //display success message if added
        <div class="alert alert-success" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message == "Creation Failed")
    {
        //display fail message if exception thrown
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.Message == "User Already has been entered for this practice")
    {
        //display fail message if exception thrown
        <div class="alert alert-danger" role="alert">
            @ViewBag.Message
        </div>
    }
    else
    {

    }
}
<a href=@Url.Action("ListAttendance", "Attendance") class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">Back to List</span>
</a>

@using (Html.BeginForm("CreatePracticeAttendance","Attendance"))
{
    <div class="form-group">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PracticeID)
        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.UserID, Model.GetUsers(users.TeamID), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Attended, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Attended)
                    @Html.ValidationMessageFor(model => model.Attended, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


<a href=@Url.Action("ListPracticeAttendance", "Attendance") class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">View All Practice Attendance</span>
</a>

SportsMGMTApp/Views/Attendance/ListAttendance.cshtml
@model List<SportsMGMTCommon.Practice>

@{
    ViewBag.Title = "Practice Attendance";
}



<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Create Practice Attendance</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Practice Type
                        </th>
                        <th>
                            Start-Time
                        </th>
                        <th>
                            End-Time
                        </th>
                        <th>Create Attendance</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.PracticeType)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.StartTime)
                            </td>
                            <td>@Html.DisplayFor(modelItem=>item.EndTime)</td>
                            <td>
                                @Html.ActionLink("Create Attendance", "CreatePracticeAttendance", new { id = item.PracticeID })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

SportsMGMTApp/Views/Attendance/ListGameAttendance.cshtml
@model List<SportsMGMTCommon.Game>

@{

}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Create Game Attendance</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>     
                        <tr>
                            <th>
                                Game
                            </th>
                            <th>
                               Start-Time
                            </th>
                            <th>
                             End-Time
                            </th>
                            <th>
                                Home Team
                            </th>
                            <th>
                                Away Team
                            </th>
                            <th>
                               Home Team Score
                            </th>
                            <th>
                              Away Team Score
                            </th>
                            <th> Create New Attendnace</th>
                        </tr>
                        </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.FormatValue(item.GameID,SportsMGMTApp.Models.GameAttendanceModel.FormatGameIDs(item.GameID))
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StartTime)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EndTime)
                                </td>
                                <td>
                                    @Html.FormatValue(item.HomeTeam,SportsMGMTApp.Models.GameModel.GetTeamNameString(item.HomeTeam))
                                </td>
                                <td>
                                    @Html.FormatValue(item.AwayTeam,SportsMGMTApp.Models.GameModel.GetTeamNameString(item.AwayTeam))
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.HomeTeamScore)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.AwayTeamScore)
                                </td>
                                <td>
                                    @*@Html.ActionLink("Create New Attendance", "CreateGameAttendance", new { id = item.GameID }) |*@
                                    @Html.ActionLink("Add Stat", "CreatePlayerStats", new { Controller = "Stats", Action = "CreatePlayerStats", id = item.GameID })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

SportsMGMTApp/Views/Attendance/ListPracticeAttendance.cshtml
@model List<SportsMGMTCommon.PracticeAttended>

@{
    
}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">View All Attendance</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Practice Type
                        </th>
                        <th>
                            Teammate Name
                        </th>
                        <th>
                            Did Attend?
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.FormatValue(item.PracticeID,SportsMGMTApp.Models.PracticeAttendanceModel.FormatPracticeID(item.PracticeID))
                        </td>
                        <td>
                            @Html.FormatValue(item.UserID,SportsMGMTApp.Models.PracticeAttendanceModel.GetUserName(item.UserID))
                        </td>
                        <td>
                            @Html.FormatValue(item.Attended,SportsMGMTApp.Models.PracticeAttendanceModel.FormatBool(item.Attended))
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
 
        <a href=@Url.Action("ListAttendance", "Attendance") class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">Create New</span>
</a>

SportsMGMTApp/Views/Attendance/ViewGameAttendance.cshtml
@model List<SportsMGMTCommon.GameAttendance>

@{
    ViewBag.Title = "ViewGameAttendance";
}

<h2>ViewGameAttendance</h2>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">All Attendance</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Home Team Vs AwayTeam
                        </th>
                        <th>
                            PlayerName
                        </th>
                        <th>
                            Attended?
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            @{ if (item != null)
                                {
                            <td>
                                @Html.FormatValue(item.GameID, SportsMGMTApp.Models.GameAttendanceModel.FormatGameIDs(item.GameID))
                            </td>
                            <td>
                                @Html.FormatValue(item.UserID, SportsMGMTApp.Models.GameAttendanceModel.GetUserName(item.UserID))
                            </td>
                            <td>
                                @Html.FormatValue(item.Attended, SportsMGMTApp.Models.GameAttendanceModel.FormatAttend(item.Attended))
                            </td>
                                }
                                else
                                {
                                    <td>
                                        No Attendance Recorded
                                    </td>
                                    <td>
                                        No Attendance Recorded
                                    </td>
                                    <td>
                                        No Attendance Recorded
                                    </td>
                                }
                                }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<a href=@Url.Action("ListGameAttendance", "Attendance") class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">Create New</span>
</a>